name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy'
        required: true
        default: dev

jobs:
  build:
    name: Build Resources for ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_ENV: ${{ github.event.inputs.env }}
      TF_BACKEND_BUCKET: gh-tf-ci-state
      TF_ENV_DIR: environments/${{ github.event.inputs.env }}
      TF_BACKEND_KEY: environments/${{ github.event.inputs.env }}/terraform.tfstate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}      

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: |
          terraform -chdir=${TF_ENV_DIR} init \
          -backend-config="bucket=${TF_BACKEND_BUCKET}" \
          -backend-config="key=${TF_BACKEND_KEY}"

      - name: Terraform Validate
        run: terraform -chdir=${TF_ENV_DIR} validate

      - name: Terraform Plan
        run: terraform -chdir=${TF_ENV_DIR} plan

      # - name: Terraform Apply
      #   run: terraform -chdir=${TF_ENV_DIR} apply -auto-approve        