name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  id-token: write   
  contents: read    

env:
  AWS_REGION: us-east-1
  TF_ENV: ${{ github.event.inputs.env || 'dev' }}
  TF_BACKEND_BUCKET: gh-tf-ci-state

jobs:

  validate-and-plan:
    name: Validate & Plan Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183909166:role/terraform-oidc
          aws-region: ${{ env.AWS_REGION }}  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          TF_ENV_DIR="environments/${TF_ENV}"
          terraform -chdir=${TF_ENV_DIR} validate

      - name: Terraform Init
        run: |
          TF_ENV_DIR="environments/${TF_ENV}"
          TF_BACKEND_KEY="environments/${TF_ENV}/${GITHUB_ACTOR}/terraform.tfstate"        
          terraform -chdir=${TF_ENV_DIR} init \
          -backend-config="bucket=${TF_BACKEND_BUCKET}" \
          -backend-config="key=${TF_BACKEND_KEY}"

      - name: Terraform Plan
        run: |
          TF_ENV_DIR="environments/${TF_ENV}"
          terraform -chdir=${TF_ENV_DIR} plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.actor }}
          path: environments/${{ github.event.inputs.env }}/${{ github.actor }}/tfplan

  apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    needs: validate-and-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183909166:role/terraform-oidc
          aws-region: ${{ env.AWS_REGION }}  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Apply
        run: |
          TF_ENV_DIR="environments/${TF_ENV}"
          TF_BACKEND_KEY="environments/${{ github.event.inputs.env }}/${{ github.actor }}/terraform.tfstate"
          terraform -chdir=$TF_ENV_DIR init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=$TF_BACKEND_KEY"
          terraform -chdir=${TF_ENV_DIR} apply -auto-approve